# This is a basic workflow that is manually triggered

name: Windows Pipeline

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
    - dev-*
    tags:
    - release-v*.*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  Build:
    # The type of runner that the job will run on
    runs-on: windows-2022
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
      with:
        submodules: "recursive"
    - name: Setup node
      uses: actions/setup-node@v2.5.1    
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        # The preferred processor architecture of MSBuild. Can be either "x86" or "x64". "x64" is only available from Visual Studio version 17.0 and later.
        msbuild-architecture: x64
    - name: Compile
      run: |
        cd armorpaint
        node armorcore/make -g direct3d11
        cd armorcore
        7z x v8\libraries\win32\release\v8_monolith.7z -ov8\libraries\win32\release -y
        git apply patch/window_handling.diff --directory=Kinc
        node Kinc/make -g direct3d11
    - name: Build
      run: |
        cd armorpaint
        cd armorcore
        msbuild build/ArmorPaint.sln /p:Configuration=Release /p:Platform=x64
    - name: Create Artifact
      run: |
        cd armorpaint
        cp -r armorcore/build/x64/Release/* build/
        7z a armorpaint-${{github.ref_name}}.zip build
        ls
    - name: Push Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: armorpaint-artifacts
        path: armorpaint/armorpaint-${{github.ref_name}}.zip
        if-no-files-found: error
  # Release:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest
  #   needs: Build
  #   permissions:
  #     contents: write
  #   steps:
  #   - name: Pull Artifact
  #     uses: actions/download-artifact@v2.1.0
  #     with:
  #       name: armorpaint-artifacts
  #   - name: Release Artifact
  #     uses: softprops/action-gh-release@v1
  #     with:
  #       name: ${{github.ref_name}}
  #       files: armorpaint-*.zip
